#!/bin/bash

BASEDIR=$(cd "$(dirname "$0")"; pwd)
TMPDIR=tmp
NGINXV=nginx-1.2.5
NGINXDIR=$NGINXV/

# Create and move into the tmp dirctory
mkdir -p $TMPDIR
cd $TMPDIR

# Download nginx source
if [ ! -f $NGINXV.tar.gz ]; then
	curl http://nginx.org/download/$NGINXV.tar.gz -o $NGINXV.tar.gz
fi

# Unpack nginx source
tar zxvf ./$NGINXV.tar.gz

cd ./$NGINXDIR

# Configure and make
./configure --prefix=. --sbin-path=bin/ --conf-path=conf/nginx.conf --error-log-path=logs/error.log --http-client-body-temp-path=tmp/client_body_temp/ --http-proxy-temp-path=tmp/proxy_temp/ --http-fastcgi-temp-path=tmp/fastcgi_temp/ --http-uwsgi-temp-path=tmp/uwsgi_temp/ --http-scgi-temp-path=tmp/scgi_temp/ --with-ipv6 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_fastcgi_module

make

# Move bin file into appropriate dir
if [ ! -d $BASEDIR/bin/ ]; then
	mkdir $BASEDIR/bin
fi

cp -f objs/nginx $BASEDIR/bin/

cd $BASEDIR

# Remove the temporary directory
rm -r $TMPDIR/$NGINXV && rm -r $TMPDIR/$NGINXV.tar.gz
