#!/bin/sh

CURRENTDIR=`pwd`
BASEDIR=$(cd "$(dirname "$0")"; pwd)
NGINXDIR=$BASEDIR/nginx/bin
PIDFILE=$BASEDIR/nginx/log/nginx.pid

start()
{
	$NGINXDIR/nginx
}

stop()
{
	$NGINXDIR/nginx -s stop
}

reload()
{
	$NGINXDIR/nginx -s reload
}

restart()
{
	stop_nginx
	start_nginx
}

cd $BASEDIR

case $1 in
        'start')

                # Start nginx
                start
                ;;

        'stop')

                # Stop nginx
                stop
                ;;

        'reload')
		
                # Reload nginx
                reload	
		;;

        'restart')
		
                # Retart nginx
                restart
		;;
esac

cd $CURRENTDIR

exit 0
